import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/provider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryClientProvider } from "@/lib/queryClient/queryClient";
import { PersistGateProvider } from "@/lib/persistor/persistGate";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <PersistGateProvider>
            <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
          </PersistGateProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
